version: '3'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: always
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:8000:8000
    environment:
      VIRTUAL_HOST: ${PORTAINER_URL}
      VIRTUAL_PORT: ${PORTAINER_PORT}
      LETSENCRYPT_HOST: ${PORTAINER_URL}
      LETSENCRYPT_MAIL: ${SSL_MAIL}

networks:
  default:
    external:
      name: devproxy

