version: '3.3'

services:
  db-core:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/sql:/mnt
    restart: always
    container_name: db-core
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      default:
        ipv4_address: 172.25.0.200

  db-admin:
    depends_on:
      - db-core
    image: phpmyadmin/phpmyadmin
    environment:
      VIRTUAL_HOST: phpmyadmin.local
      PMA_HOST: db-core
    container_name: db-admin
    volumes:
      - ./data/pma/sessions:/sessions
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    networks:
      default:
        ipv4_address: 172.25.0.201

networks:
  default:
    external:
      name: ${NET_NAME}